In [2]:
import pandas as pd      # load the pandas library and call it pd
import numpy as np       # load numpy and call it np

df = pd.read_csv("data/raw/student_performance_raw.csv")
print(df.shape)
df.head()

(205, 10)

,Student_ID,Gender,Section,Attendance_Percent,Study_Hours_Per_Week,Mathematics,Python_Programming,Computer_Fundamentals,English,Statistics
0,S001,Male,C,80.7,11.4,50.0,66.0,75.0,52.0,61.0
1,S002,Female,C,74.1,17.5,52.0,68.0,75.0,63.0,68.0
2,S003,Male,A,64.8,13.8,58.0,56.0,58.0,62.0,48.0
3,S004,male,A,56.8,7.7,34.0,33.0,50.0,39.0,32.0
4,S005,Male,B,69.6,6.4,45.0,52.0,55.0,51.0,45.0

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print(list(df.columns))

Rows: 205
Columns: 10
['Student_ID', 'Gender', 'Section', 'Attendance_Percent', 'Study_Hours_Per_Week', 'Mathematics', 'Python_Programming', 'Computer_Fundamentals', 'English', 'Statistics']

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             205 non-null    str
 1   Gender                 205 non-null    str
 2   Section                205 non-null    str
 3   Attendance_Percent     205 non-null    float64
 4   Study_Hours_Per_Week   203 non-null    float64
 5   Mathematics            200 non-null    float64
 6   Python_Programming     205 non-null    float64
 7   Computer_Fundamentals  205 non-null    float64
 8   English                205 non-null    float64
 9   Statistics             202 non-null    float64
dtypes: float64(7), str(3)
memory usage: 16.1 KB

In [5]:
df.isnull().sum()      # counts empty cells in each column

Student_ID               0
Gender                   0
Section                  0
Attendance_Percent       0
Study_Hours_Per_Week     2
Mathematics              5
Python_Programming       0
Computer_Fundamentals    0
English                  0
Statistics               3
dtype: int64

In [6]:
print("Duplicate rows:", df.duplicated().sum())
df[df.duplicated()]    # shows the duplicate rows

Duplicate rows: 5

,Student_ID,Gender,Section,Attendance_Percent,Study_Hours_Per_Week,Mathematics,Python_Programming,Computer_Fundamentals,English,Statistics
200,S059,Male,B,60.6,4.8,37.0,45.0,47.0,40.0,39.0
201,S041,Male,C,75.8,6.1,38.0,63.0,55.0,52.0,59.0
202,S035,Female,A,100.0,18.2,63.0,70.0,82.0,65.0,70.0
203,S103,Female,B,78.4,16.7,65.0,69.0,66.0,57.0,44.0
204,S185,Male,A,75.3,10.1,56.0,56.0,66.0,55.0,54.0

In [7]:
df.describe()

,Attendance_Percent,Study_Hours_Per_Week,Mathematics,Python_Programming,Computer_Fundamentals,English,Statistics
count,205.000000,203.000000,200.000000,205.000000,205.000000,205.000000,202.000000
mean,75.691707,9.802463,50.155000,56.273171,60.370732,55.936585,48.222772
std,11.278962,4.134274,10.240867,9.542655,9.918744,10.254644,10.343594
min,40.000000,1.000000,17.000000,26.000000,36.000000,27.000000,19.000000
25%,67.500000,6.800000,44.000000,51.000000,55.000000,49.000000,41.000000
50%,75.800000,9.800000,50.000000,56.000000,61.000000,55.000000,48.000000
75%,82.800000,12.500000,57.000000,63.000000,66.000000,62.000000,54.000000
max,105.000000,22.300000,74.000000,82.000000,94.000000,82.000000,75.000000

In [8]:
print(df["Gender"].value_counts())
print()
print(df["Section"].value_counts())

Gender
Male      101
Female    101
male        1
F           1
FEMALE      1
Name: count, dtype: int64

Section
A    75
C    67
B    63
Name: count, dtype: int64

In [9]:
df.describe().loc[["min", "max"]]

,Attendance_Percent,Study_Hours_Per_Week,Mathematics,Python_Programming,Computer_Fundamentals,English,Statistics
min,40.0,1.0,17.0,26.0,36.0,27.0,19.0
max,105.0,22.3,74.0,82.0,94.0,82.0,75.0

In [10]:
# copy() makes a separate table, so df (the raw data) is never changed
df_clean = df.copy()

In [11]:
# drop_duplicates() removes rows that are exact copies of earlier rows
# reset_index() renumbers the rows 0, 1, 2... after rows are removed
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
print("Rows after removing duplicates:", len(df_clean))   # should be 200

Rows after removing duplicates: 200

In [12]:
# strip() removes extra spaces, lower() makes everything lowercase
# map() then replaces each spelling with one standard value
df_clean["Gender"] = (
    df_clean["Gender"].str.strip().str.lower()
    .map({"male": "Male", "female": "Female", "f": "Female"})
)
print(df_clean["Gender"].value_counts())

Gender
Female    101
Male       99
Name: count, dtype: int64

In [13]:
# Attendance above 100 is impossible, so we replace it with NaN (missing)
df_clean.loc[df_clean["Attendance_Percent"] > 100, "Attendance_Percent"] = np.nan
print(df_clean["Attendance_Percent"].max())

100.0

In [14]:
cols = ["Attendance_Percent", "Study_Hours_Per_Week", "Mathematics", "Statistics"]
for col in cols:
    # median is the middle value, so it is not pulled by extreme values
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

print(df_clean.isnull().sum())   # everything should now be 0

Student_ID               0
Gender                   0
Section                  0
Attendance_Percent       0
Study_Hours_Per_Week     0
Mathematics              0
Python_Programming       0
Computer_Fundamentals    0
English                  0
Statistics               0
dtype: int64

In [15]:
import os
print("Shape:", df_clean.shape)
print("Duplicates:", df_clean.duplicated().sum())

os.makedirs("data/processed", exist_ok=True)       # creates the folder if missing
df_clean.to_csv("data/processed/student_performance_clean.csv", index=False)
print("Clean file saved!")

Shape: (200, 10)
Duplicates: 0
Clean file saved!

In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/processed/student_performance_clean.csv")
print(df.shape)       # should be (200, 10)
df.head()

(200, 10)

,Student_ID,Gender,Section,Attendance_Percent,Study_Hours_Per_Week,Mathematics,Python_Programming,Computer_Fundamentals,English,Statistics
0,S001,Male,C,80.7,11.4,50.0,66.0,75.0,52.0,61.0
1,S002,Female,C,74.1,17.5,52.0,68.0,75.0,63.0,68.0
2,S003,Male,A,64.8,13.8,58.0,56.0,58.0,62.0,48.0
3,S004,Male,A,56.8,7.7,34.0,33.0,50.0,39.0,32.0
4,S005,Male,B,69.6,6.4,45.0,52.0,55.0,51.0,45.0

In [17]:
# a list of the five subject columns, so we can reuse it
subjects = ["Mathematics", "Python_Programming", "Computer_Fundamentals",
            "English", "Statistics"]

# agg() applies several functions at once; round(2) keeps 2 decimal places
summary = df[subjects].agg(["mean", "median", "min", "max", "std"]).round(2)
summary.T      # .T flips the table so each subject is one row

                        mean  median   min   max    std
Mathematics            50.11    50.0  17.0  74.0  10.06
Python_Programming     56.16    56.0  26.0  82.0   9.52
Computer_Fundamentals  60.30    61.0  36.0  94.0   9.86
English                55.99    55.0  27.0  82.0  10.30
Statistics             48.10    48.0  19.0  75.0  10.22

In [18]:
subject_means = df[subjects].mean().round(2)
print("Highest average:", subject_means.idxmax(), "-", subject_means.max())
print("Lowest average: ", subject_means.idxmin(), "-", subject_means.min())

Highest average: Computer_Fundamentals - 60.3
Lowest average:  Statistics - 48.1

In [19]:
df[["Attendance_Percent", "Study_Hours_Per_Week"]].agg(
    ["mean", "median", "min", "max", "std"]).round(2)

        Attendance_Percent  Study_Hours_Per_Week
mean                 75.49                  9.77
median               75.80                  9.75
min                  40.00                  1.00
max                 100.00                 22.30
std                  11.04                  4.07

In [20]:
# mean(axis=1) averages across the columns of each row (one student)
# This is a NEW calculated column, not part of the original dataset
df["Average_Marks"] = df[subjects].mean(axis=1).round(2)
df["Average_Marks"].describe().round(2)

count    200.00
mean      54.13
std        7.16
min       33.00
25%       50.00
50%       54.60
75%       58.45
max       75.80
Name: Average_Marks, dtype: float64